export const types = {

    // login
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',

    // error
    SET_ERROR: 'SET_ERROR',
    UNSET_ERROR: 'UNSET_ERROR',

    // loading
    START_LOADIN: 'START_LOADIN',
    FINISH_LOADING: 'FINISH_LOADING',

    // notes
    NOTE_ADD_NEW: 'NOTE_ADD_NEW',
    NOTE_ACTIVE: 'NOTE_ACTIVE',
    NOTE_LOADING: 'NOTE_LOADING',
    NOTE_UPDATE: 'NOTE_UPDATE',
    NOTE_FILE_URL: 'NOTES_FILE_URL',
    NOTE_DELETE: 'NOTE_DELETE',
    NOTE_LOGOUT_CLEANING: 'NOTE_LOGOUT_CLEANING',

}